import { defineSiteGuideCatalog } from '@clearrights/sdk/site-guide'

export const waypointSiteGuideCatalog = defineSiteGuideCatalog({
  version: 'waypoint-site-guide-2026.1',
  destinations: [
    {
      id: 'bookings',
      label: 'Bookings',
      summary: 'Review upcoming trips and booking details.',
      category: 'Trips',
      keywords: ['trips', 'reservations', 'upcoming'],
      target: { kind: 'route', path: '/', hash: '#/?focus=upcoming-trips' },
    },
    {
      id: 'passenger-details',
      label: 'Passenger details',
      summary: 'Understand the passenger information used for a booking.',
      category: 'Account and booking',
      keywords: ['travellers', 'identity', 'passengers'],
      target: { kind: 'route', path: '/', hash: '#/info/passenger-details' },
    },
    {
      id: 'payment-methods',
      label: 'Payment methods',
      summary: 'Review how payment methods are represented in this demo.',
      category: 'Account and booking',
      keywords: ['cards', 'billing', 'wallet'],
      target: { kind: 'route', path: '/', hash: '#/info/payment-methods' },
    },
    {
      id: 'privacy-choices',
      label: 'Privacy choices',
      summary: 'Inspect and change Waypoint privacy processing choices.',
      category: 'Privacy',
      keywords: ['consent', 'processing', 'data-controls'],
      target: { kind: 'panel', panel: 'personal_controls', section: 'privacy' },
    },
    {
      id: 'privacy-notice',
      label: 'Privacy notice',
      summary: 'Read the fictional Waypoint privacy notice.',
      category: 'Privacy',
      keywords: ['disclosure', 'legal', 'data-policy'],
      target: { kind: 'route', path: '/', hash: '#/info/privacy-notice' },
    },
    {
      id: 'cookie-details',
      label: 'Cookie details',
      summary: 'Read how browser storage is used in the local demo.',
      category: 'Privacy',
      keywords: ['cookies', 'tracking', 'browser-storage'],
      target: { kind: 'route', path: '/', hash: '#/info/cookie-details' },
    },
    {
      id: 'accessibility-preferences',
      label: 'Accessibility preferences',
      summary: 'Adjust text size, contrast, motion, and reading layout.',
      category: 'Accessibility',
      keywords: ['display', 'motion', 'contrast'],
      target: { kind: 'panel', panel: 'personal_controls', section: 'accessibility' },
    },
    {
      id: 'accessibility-statement',
      label: 'Accessibility statement',
      summary: 'Read the fictional Waypoint accessibility statement.',
      category: 'Accessibility',
      keywords: ['inclusive', 'assistive', 'standards'],
      target: { kind: 'route', path: '/', hash: '#/info/accessibility-statement' },
    },
    {
      id: 'cancellation-policy',
      label: 'Cancellation policy',
      summary: 'Review the demo cancellation and refund rules.',
      category: 'Policies',
      keywords: ['refunds', 'changes', 'cancel'],
      target: { kind: 'route', path: '/', hash: '#/info/cancellation-policy' },
    },
    {
      id: 'help-and-support',
      label: 'Help and support',
      summary: 'Find common help topics for Waypoint trips.',
      category: 'Support',
      keywords: ['faq', 'assistance', 'support-center'],
      target: { kind: 'route', path: '/', hash: '#/info/help-and-support' },
    },
    {
      id: 'contact-waypoint',
      label: 'Contact Waypoint',
      summary: 'See the fictional contact options used by the demo.',
      category: 'Support',
      keywords: ['email', 'phone', 'message'],
      target: { kind: 'route', path: '/', hash: '#/info/contact-waypoint' },
    },
    {
      id: 'clearrights-developer-integration',
      label: 'ClearRights developer integration',
      summary: 'Inspect the SDK architecture, active adapters, and trust boundaries.',
      category: 'Developer',
      keywords: ['sdk', 'webmcp', 'developer'],
      target: { kind: 'route', path: '/', hash: '#/clearrights' },
    },
  ],
})
