import { definePrivacyCatalog } from '@/domain'

export const travelCatalog = definePrivacyCatalog({
  version: 'waypoint-travel-2026.2',
  noticeVersion: 'waypoint-privacy-choices-2026.2',
  sections: [
    {
      id: 'essential_services',
      label: 'Essential services',
      description: 'Needed to provide booked trips and protect your account.',
    },
    {
      id: 'personalisation',
      label: 'Personalisation',
      description: 'Controls experiences adapted to your interests.',
    },
    {
      id: 'location',
      label: 'Location',
      description: 'Controls features that use your precise location.',
    },
    {
      id: 'partner_offers',
      label: 'Partner offers',
      description: 'Controls tailored offers from selected partners.',
    },
  ],
  processing: [
    {
      id: 'trip_fulfilment',
      sectionId: 'essential_services',
      label: 'Trip fulfilment',
      group: 'required',
      locked: true,
      defaultEnabled: true,
      purpose: 'Create, manage, and complete the trips you book.',
      data: ['Traveller identity', 'Booking details', 'Payment status'],
      declaredLegalBasis: 'contract',
      control: 'Required while using booking services.',
      dependencies: [],
      consequence: 'Trips could not be booked or managed.',
      policyReference: 'Waypoint Demo Privacy Notice §2.1',
      capabilities: ['book_and_manage_trips'],
      uses: ['booking_operations'],
    },
    {
      id: 'account_security',
      sectionId: 'essential_services',
      label: 'Account security',
      group: 'required',
      locked: true,
      defaultEnabled: true,
      purpose: 'Detect suspicious access and protect the demo account.',
      data: ['Sign-in events', 'Device information', 'Security signals'],
      declaredLegalBasis: 'legitimate_interest',
      control: 'Required to protect the account.',
      dependencies: [],
      consequence: 'Account protection would be reduced.',
      policyReference: 'Waypoint Demo Privacy Notice §2.2',
      capabilities: ['protect_account'],
      uses: ['fraud_prevention'],
    },
    {
      id: 'transactional_updates',
      sectionId: 'essential_services',
      label: 'Transactional updates',
      group: 'required',
      locked: true,
      defaultEnabled: true,
      purpose: 'Send confirmations, schedule changes, and essential trip notices.',
      data: ['Contact details', 'Booking status', 'Journey schedule'],
      declaredLegalBasis: 'contract',
      control: 'Required for active bookings.',
      dependencies: ['trip_fulfilment'],
      consequence: 'Essential booking updates could not be delivered.',
      policyReference: 'Waypoint Demo Privacy Notice §2.3',
      capabilities: ['receive_trip_updates'],
      uses: ['service_communications'],
    },
    {
      id: 'recommendations',
      sectionId: 'personalisation',
      label: 'Recommendations',
      group: 'optional',
      locked: false,
      defaultEnabled: true,
      purpose: 'Suggest destinations and itineraries based on travel preferences.',
      data: ['Travel preferences', 'Viewed destinations', 'Past trips'],
      declaredLegalBasis: 'consent',
      control: 'Can be changed after human review.',
      dependencies: ['trip_fulfilment'],
      consequence: 'Destination and itinerary suggestions will be generic.',
      policyReference: 'Waypoint Demo Privacy Notice §3.1',
      capabilities: ['personalised_recommendations'],
      uses: ['preference_personalisation'],
    },
    {
      id: 'location_suggestions',
      sectionId: 'location',
      label: 'Location suggestions',
      group: 'optional',
      locked: false,
      defaultEnabled: true,
      purpose: 'Suggest nearby places during a trip.',
      data: ['Precise location', 'Destination context'],
      declaredLegalBasis: 'consent',
      control: 'Can be changed after human review.',
      dependencies: ['trip_fulfilment'],
      consequence: 'Nearby place suggestions will no longer be available.',
      policyReference: 'Waypoint Demo Privacy Notice §3.2',
      capabilities: ['nearby_suggestions'],
      uses: ['precise_location'],
    },
    {
      id: 'partner_advertising',
      sectionId: 'partner_offers',
      label: 'Partner advertising',
      group: 'optional',
      locked: false,
      defaultEnabled: true,
      purpose: 'Tailor advertising from selected travel partners.',
      data: ['Travel interests', 'Partner engagement'],
      declaredLegalBasis: 'consent',
      control: 'Can be changed after human review.',
      dependencies: [],
      consequence: 'Partner offers will no longer be personalised.',
      policyReference: 'Waypoint Demo Privacy Notice §3.3',
      capabilities: ['partner_offers'],
      uses: ['partner_marketing'],
    },
  ],
  capabilities: [
    { id: 'book_and_manage_trips', label: 'Book and manage trips', description: 'Keep booking and trip management available.' },
    { id: 'protect_account', label: 'Protect the account', description: 'Keep account security checks active.' },
    { id: 'receive_trip_updates', label: 'Receive trip updates', description: 'Keep essential booking messages.' },
    { id: 'personalised_recommendations', label: 'Personalised recommendations', description: 'Keep suggestions based on travel preferences.' },
    { id: 'nearby_suggestions', label: 'Nearby suggestions', description: 'Keep suggestions based on current location.' },
    { id: 'partner_offers', label: 'Partner offers', description: 'Keep tailored offers from travel partners.' },
  ],
  uses: [
    { id: 'booking_operations', label: 'Booking operations', description: 'Use data to create and manage trips.' },
    { id: 'fraud_prevention', label: 'Fraud prevention', description: 'Use security signals to protect the account.' },
    { id: 'service_communications', label: 'Service communications', description: 'Use contact details for essential trip updates.' },
    { id: 'preference_personalisation', label: 'Preference personalisation', description: 'Use travel interests to personalise recommendations.' },
    { id: 'precise_location', label: 'Precise location', description: 'Use current location for nearby suggestions.' },
    { id: 'partner_marketing', label: 'Partner marketing', description: 'Use travel interests for partner advertising.' },
  ],
})
